markdown: rdiscount
author: RootKiter
name: RootKiter
markdown: redcarpet
pygments: true
email: qwj__164521@126.com
domain: github.io
title: rootkiter
rssurl: http://rootkiter.github.io/atom.xml
defmusic: http://rootkiter.github.io/music/backmusic.mp3
defimg: http://rootkiter.github.io/image/background.jpeg
