markdown: rdiscount
author: RootKiter
name: RootKiter
markdown: redcarpet
pygments: true
email: 2559964169@qq.com
domain: rootkiter.com
title: rootkiter
rssurl: http://rootkiter.github.io/atom.xml
defmusic: http://rootkiter.github.io/music/backmusic.mp3
defimg: http://rootkiter.github.io/image/background.jpeg
